# Generated by Django 4.1 on 2022-12-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='bactchtiming',
            new_name='batchtiming',
        ),
    ]
