# Generated by Django 4.1 on 2022-12-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_bactchtiming_batch_batchtiming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchinfo',
            old_name='Batch',
            new_name='batch',
        ),
    ]
