# Generated by Django 4.1 on 2022-12-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_batch_batchinfo_batch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BatchInfo',
            new_name='BatchesInfo',
        ),
    ]
