# Generated by Django 4.1 on 2022-12-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_firstname_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
