# Generated by Django 4.1 on 2022-12-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_batch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='id',
            new_name='_id',
        ),
    ]
