# Generated by Django 4.1 on 2022-12-10 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_id_batch__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='batchesinfo',
            name='batch',
            field=models.ForeignKey(default=44, on_delete=django.db.models.deletion.CASCADE, to='api.batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchesinfo',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchesinfo',
            name='person',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
            preserve_default=False,
        ),
    ]
