# Generated by Django 4.1 on 2022-12-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_batch__id_alter_batchesinfo_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchesinfo',
            name='month',
            field=models.CharField(default=2344, max_length=100),
            preserve_default=False,
        ),
    ]
