# Generated by Django 4.1 on 2022-12-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_batchesinfo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchesinfo',
            name='enrollDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
